export {
	RequireAuth,
	loginHandler,
	registerHandler,
	setValueHandler,
	setTestHandler,
	setFocusHandler,
} from "./authentication";
export {
	removeFromArray,
	removeFromDateArray,
	presentInArray,
	presentObjInArray,
	removeObjFromArray,
	updateObjInArray,
	updateAddressObjInArray,
	getDataFromId,
	checkIdPresentInArray,
	getDataFromPlaylist,
	getVideosFromPlaylist,
	getCountValue,
	trimData,
	updateHabitsDate,
	findDateInArray,
	getHabitData,
	getStreaks,
	addNoteToHabits,
	deleteNoteFromHabits,
} from "./helpers";
